DELETE http://localhost:3001/api/persons/5f0868f5f27a2938ac77d190 HTTP/1.1
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Arto",
    "number": "040-1"
}
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "040-123456789102"
}

###
GET http://localhost:3001/api/persons HTTP/1.1
###
GET http://localhost:3001/api/persons/5f0868f5f27a2938ac77d190 HTTP/1.1
